<?php

/**
 * UW Weather Block Module - a Drupal module to displa a block containing UW 
 *    Weather Station Data
 *
 * Copyright (C) 2011 Eric Gerlach
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

/** 
 * Display help and module information
 * @param path Which path of the site are we displaying help for
 * @param arg Array that holds the current path as would be returned from arg() 
 *            function
 * @return Help text for the path
 */

function uw_weather_block_help($path, $arg)
{
  $output = '';
  switch($path)
  {
    case 'admin/help#uw_weather_block':
      $output = '<p>' . t('Creates a block which displays the current weather according to the UW Weather Station.') . '</p>';
      break;
  }
  return $output;
} // function uw_weather_block_help

/**
 * Implementation of hook_block()
 * @param string $op one of "list", "view", "save" and "configure"
 * @param integer $delta code to identify the block
 * @param array $edit only for "save" operation
 */
function uw_weather_block_block($op = 'list', $delta = 0, $edit = array())
{
  switch ($op)
  {
    case 'list':
      $block = array();
      $block[0] = array(
        'info' => 'Current UW Weather',
      );
      return $block;
      break;
    case 'view':
      $block = array(
        'subject' => 'UW Weather',
        'content' => uw_weather_block_contents(),
      );
      return $block;
      break;
  }
} // function uw_weather_block_block

/**
 * Generate the content for the block
 */
function uw_weather_block_contents()
{
  $data = file_get_contents('http://weather.uwaterloo.ca/waterloo_weather_station_data.xml');
  $weather = new SimpleXMLElement($data);

  $output  = '';
  $output .= "Temperature: " . $weather->temperature_current_C . "<br/>";
  if (uw_weather_block_is_not_na($weather->windchill_C)) {
    $output .= "Windchill: " . $weather->windchill_C . "<br/>";
  }
  
  return $output;
}

/**
 * Tests a value that comes back from the Weather Station to make sure it's not N/A
 */
function uw_weather_block_is_not_na($value)
{
  $string = sprintf("%s", $value);
  $string = substr($string, 0, 3);
  return $string != 'N_A';
}

